name: Lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ruff:
    name: Ruff linting and uv lock
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - run: uv run pre-commit run --all-files --show-diff-on-failure
